import os
import json
import glob
from pathlib import Path

def get_plugin_info(plugin_dir):
    manifest = plugin_dir / ".claude-plugin" / "plugin.json"
    if manifest.exists():
        try:
            with open(manifest, "r", encoding="utf-8") as f:
                data = json.load(f)
                return data.get("name"), data.get("description")
        except:
            pass
    return plugin_dir.name, "No description available"

def scan_directory(root_path, label):
    print(f"\n### {label} ({root_path})")
    root = Path(root_path).expanduser().resolve()
    
    if not root.exists():
        print(f"_Directory not found._")
        return

    # Scan for Plugins
    plugins = []
    for item in root.iterdir():
        if item.is_dir() and not item.name.startswith("."):
            name, desc = get_plugin_info(item)
            # Check for skills inside
            skills = []
            skills_dir = item / "skills"
            if skills_dir.exists():
                skills = [s.name for s in skills_dir.iterdir() if s.is_dir() and not s.name.startswith(".")]
            
            plugins.append({
                "name": name,
                "description": desc,
                "skills": skills
            })
    
    if plugins:
        for p in plugins:
            print(f"- **{p['name']}**: {p['description']}")
            if p['skills']:
                print(f"  - Skills: {', '.join(p['skills'])}")
    else:
        # It might be a direct command folder like .claude/commands
        md_files = list(root.glob("*.md"))
        if md_files:
             for f in md_files:
                 print(f"- Command: `{f.stem}`")
        else:
            print("_No plugins or commands found._")

def main():
    print("# Claude/Gemini Capability Inventory")
    print("\nGenerated by `plugins/google-ecosystem/scripts/generate_inventory.py`\n")

    # 1. Project Commands
    scan_directory(".claude/commands", "Project Commands")

    # 2. Project Plugins (Repo)
    scan_directory("plugins", "Repository Plugins")

    # 3. Global Plugins
    # Windows specific path handling
    global_path = os.path.expanduser("~/.claude/plugins/marketplaces")
    if os.name == 'nt':
         # Try the specific Windows path if the expanduser doesn't map to the expected one for .claude
         alt_path = Path(os.environ['USERPROFILE']) / ".claude" / "plugins" / "marketplaces"
         if alt_path.exists():
             global_path = alt_path

    if Path(global_path).exists():
        print(f"\n### Global Plugins ({global_path})")
        # Global plugins are often nested: marketplaces/market-name/plugin-name
        for market in Path(global_path).iterdir():
            if market.is_dir():
                print(f"\n#### Marketplace: {market.name}")
                for plugin in market.iterdir():
                    if plugin.is_dir():
                        name, desc = get_plugin_info(plugin)
                        skills = []
                        skills_dir = plugin / "skills"
                        if skills_dir.exists():
                            skills = [s.name for s in skills_dir.iterdir() if s.is_dir()]
                        
                        print(f"- **{name}**: {desc}")
                        if skills:
                            print(f"  - Skills: {', '.join(skills)}")
    else:
         print(f"\n### Global Plugins")
         print("_Global plugins directory not found or empty._")

if __name__ == "__main__":
    main()
